name: Build and Push history-service

on:
  push:
    branches:
      - 'master'
    paths:
      - 'history-service/**'
      - '.github/workflows/history-service-ci.yml'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'history-service/**'
      - '.github/workflows/history-service-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./history-service  # <-- Set path to your service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22  
          cache: 'npm'
          cache-dependency-path: history-service/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test


  build-and-push:
    if: github.event_name == 'push'

    needs: test

    runs-on: ubuntu-latest
    # grant permissions for the GITHUB_TOKEN to write to github container registry
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./history-service # change this to your service, change the image names under tags below also!!
          push: true
          tags: |
            ghcr.io/cs3219-ay2526sem1/cs3219-ay2526s1-project-g17/history-service:${{ github.sha }}
            ghcr.io/cs3219-ay2526sem1/cs3219-ay2526s1-project-g17/history-service:latest
