name: matching-service-ci

on:
  pull_request:
    branches:
      - master
    paths:
      - 'matching_service_v2/**'
      - '.github/workflows/matching-service-ci.yaml'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redislabs/redisearch:latest
        ports:
          - 6380:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./matching_service_v2
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: matching_service_v2
        run: npm install

      - name: Verify environment variables
        run: |
          echo "Checking environment variables..."
          echo "NODE_ENV: $NODE_ENV"
          echo "ENV: $ENV"
          echo "PORT: $PORT"
          echo "REDIS_URL exists: $([ -n "$REDIS_URL" ] && echo "✓ Set" || echo "✗ Not set")"
          echo "AUTH0_AUDIENCE exists: $([ -n "$AUTH0_AUDIENCE" ] && echo "✓ Set" || echo "✗ Not set")"
          echo "AUTH0_DOMAIN exists: $([ -n "$AUTH0_DOMAIN" ] && echo "✓ Set" || echo "✗ Not set")"
          echo "ACCEPTANCE_TIMEOUT: $ACCEPTANCE_TIMEOUT"
        env:
          NODE_ENV: production
          ENV: PROD
          PORT: 3001
          REDIS_URL: ${{ secrets.MATCHING_SERVICE_REDIS }}
          ACCEPTANCE_TIMEOUT: 5000
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}

      - name: Test environment loading
        run: npm run test-env
        env:
          NODE_ENV: production
          ENV: PROD
          PORT: 3001
          REDIS_URL: ${{ secrets.MATCHING_SERVICE_REDIS }}
          ACCEPTANCE_TIMEOUT: 5000
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}

      - name: Run tests
        run: npm run test
        env:
          NODE_ENV: production
          ENV: PROD
          PORT: 3001
          REDIS_URL: ${{ secrets.MATCHING_SERVICE_REDIS }}
          ACCEPTANCE_TIMEOUT: 5000
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      
